"""full schema

Revision ID: c2622a30ec86
Revises: 
Create Date: 2026-03-27 18:20:39.788998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2622a30ec86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('tournament_id', sa.Integer(), nullable=False))
    op.add_column('matches', sa.Column('start_timestamp', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('status', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('round', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('venue', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('home_team_id', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('away_team_id', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('score_home', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('score_away', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('json_data', sa.JSON(), nullable=True))
    op.add_column('matches', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('matches_ut_id_fkey'), 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'tournaments', ['tournament_id'], ['id'])
    op.drop_column('matches', 'ut_id')
    op.add_column('seasons', sa.Column('tournament_id', sa.Integer(), nullable=False))
    op.add_column('seasons', sa.Column('name', sa.String(), nullable=True))
    op.add_column('seasons', sa.Column('start_date', sa.String(), nullable=True))
    op.add_column('seasons', sa.Column('end_date', sa.String(), nullable=True))
    op.add_column('seasons', sa.Column('json_data', sa.JSON(), nullable=True))
    op.add_column('seasons', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('seasons_ut_id_fkey'), 'seasons', type_='foreignkey')
    op.create_foreign_key(None, 'seasons', 'tournaments', ['tournament_id'], ['id'])
    op.drop_column('seasons', 'ut_id')
    op.add_column('tournaments', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('tournaments', sa.Column('country', sa.String(), nullable=True))
    op.add_column('tournaments', sa.Column('type', sa.String(), nullable=True))
    op.add_column('tournaments', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('tournaments', sa.Column('json_data', sa.JSON(), nullable=True))
    op.add_column('tournaments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'updated_at')
    op.drop_column('tournaments', 'json_data')
    op.drop_column('tournaments', 'priority')
    op.drop_column('tournaments', 'type')
    op.drop_column('tournaments', 'country')
    op.drop_column('tournaments', 'slug')
    op.add_column('seasons', sa.Column('ut_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'seasons', type_='foreignkey')
    op.create_foreign_key(op.f('seasons_ut_id_fkey'), 'seasons', 'tournaments', ['ut_id'], ['id'])
    op.drop_column('seasons', 'updated_at')
    op.drop_column('seasons', 'json_data')
    op.drop_column('seasons', 'end_date')
    op.drop_column('seasons', 'start_date')
    op.drop_column('seasons', 'name')
    op.drop_column('seasons', 'tournament_id')
    op.add_column('matches', sa.Column('ut_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key(op.f('matches_ut_id_fkey'), 'matches', 'tournaments', ['ut_id'], ['id'])
    op.drop_column('matches', 'updated_at')
    op.drop_column('matches', 'json_data')
    op.drop_column('matches', 'score_away')
    op.drop_column('matches', 'score_home')
    op.drop_column('matches', 'away_team_id')
    op.drop_column('matches', 'home_team_id')
    op.drop_column('matches', 'venue')
    op.drop_column('matches', 'round')
    op.drop_column('matches', 'status')
    op.drop_column('matches', 'start_timestamp')
    op.drop_column('matches', 'tournament_id')
    # ### end Alembic commands ###
