version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mysystem
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynet

  backend:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mysystem
    
    ports:
      - "8000:8000"
    networks:
      - mynet

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - mynet

volumes:
  postgres_data:

networks:
  mynet:
    driver: bridge
